### ISSUE TITLE
CMS: Custom PartialRouter does not pass route data to controller

### ISSUE THREAD

**Issue by stefanolsen** [episerver/netcore-preview#113]
I am attempting something similar to this forum thread: https://world.optimizely.com/forum/developer-forum/CMS/Thread-Container/2017/3/custom-routing-with-extra-parameters-in-action-method/

But instead of adding "myId" to the RouteData.Values property (as in the forum replies), I am adding it to RouteValues (as it is the only one available).

This, however, does not carry any value to the invoked controller action. Debugging the URL resolver pipeline, I don't see that RouteValues are ever being consumed and passed forward.

Is this a bug, or did you discontinue this feature? Is there an alternative solution to this particular case?

Builds:
- EPiServer.CMS.Core: 12.0.1

**Comment by bjuris** [comment]
cc @jbearfoot

**Comment by jbearfoot** [comment]
In CMS11 was the routing in CMS very tightly coupled to web requests, so the RouteValues you had there where actually a reference to the routevalues tied to the http context, meaning assignments where automatically available later in e.g. a controller.

In CMS12 we have tried to separate routing so we have a routing implementation inside of CMS that is decoupled from Web (meaning you can still route/generate urls in a none web context such as for example from a console application), then there is a endpoint routing on top of that when CMS is hosted in a web application. So the route values in the context in the pipeline routing is currently used to transfer data between different steps and is not tied to HttpContext.Request.RouteValues.

So that is sort of the background, we could of course return the route values from the CMS routing to the endpoint routing and then assign them to the route values on the http context. But you can basically do the same yourself in your partial router, that is if you take in a dependency to IHttpContextAccessor and then in your RoutePartial implemementation you could check if you have a HttpContext and if so assign values to HttpContext.Request.RouteValues then you will be able to access it from your controller. 
So I am leaning on that we will not pass around RouteValues (since a partial router can handle data transfer it self) to avoid "bloating" the API, but feel free to argument differently, it is definitely not carved in stone from my side.

**Comment by jbearfoot** [comment]
But if you have a controller (lets call it MyController) with an extra parameter "myId" that you want should be a segment in the url (like in the linked thread) then you do not need a partial router. Then you can just register a mapping for the controller like:
app.UseEndpoints(endpoints =>
{
    endpoints.MapContent().MapTemplate<MyController>("{myid}");
});

**Comment by stefanolsen** [comment]
Thanks for explaining, @jbearfoot.

What if I want to hide the URL segment of the child page?
So instead of an URL like `/parentpage/childpage?id=121`, I want `/parentpage/121`. In both cases, the URL should route to the child page content, with `id` as an action method parameter.

**Comment by jbearfoot** [comment]
Ok, not sure I understand the use case totally but I assume in your example above that 121 not an id of any content item, it just an id referring to something else? In that case there is really nothing in the url '/parentpage/121/' that specifies what the childpage is. So then you would need to get a reference to that in some way. But say that childpage is always a fixed reference (e.g. stored on a property on parentpage/startpage or somewhere). 
Using Alloy I added an extra property to ProductPage like:
public virtual ContentReference ChildHandlingIdParameter { get; set; }

Then I added an extra action to the DefaultPageController like:
     public ViewResult WithId(SitePageData currentPage, int id)
        {
            var model = CreateModel(currentPage);
            return View(string.Format("~/Views/{0}/Index.cshtml", currentPage.GetOriginalType().Name), model);
        }

And registered the extra action in startup like:
   endpoints.MapContent()
                    .MapTemplate<DefaultPageController>("{id:int}");

Then you could have a IPartialRouter<ProductPage, IContent> implementation like:

  public object RoutePartial(ProductPage content, UrlResolverContext segmentContext)
        {
            //handling format /parent/<id:int>
            var nextSegment = segmentContext.GetNextRemainingSegment(segmentContext.RemainingPath);
            if (int.TryParse(nextSegment.Next, out int id) && !ContentReference.IsNullOrEmpty(content.ChildHandlingIdParameter))
            {
                //Update routed content to child, need to get child id from somewhere here it is a property on parent page
                var child = _contentLoader.Get<IContent>(content.ChildHandlingIdParameter, new LoaderOptions { LanguageLoaderOption.Fallback(segmentContext.RequestedLanguage) });
                if (child is not null)
                {
                    //update content routed to
                    return child;
                }
            }

            return null;
        }

Then when accessing an url like '/en/alloy-plan/121' I get routed to the new action with currentPage as the "child" and with 'id' parameter set to '121'.
Now to also get the url '/en/alloy-plan/child?id=121' to route to same action I need to get id=121 into route values. I cant do it from the partial router since in that case matches '/en/alloy-plan/child' a content and it will not call any partial router (since there is no segment left). To handle that can I attach an event handler that transfers values from query parameters to route values, like:
 context.Locate.Advanced.GetInstance<IContentUrlResolverEvents>().ResolvedUrl += (o, e) =>
            {
                var idParameter = e.Context.Url.QueryCollection["id"];
                if (!string.IsNullOrEmpty(idParameter) && httpContextAccessor.HttpContext is not null)
                {
                    httpContextAccessor.HttpContext.Request.RouteValues["id"] = idParameter;
                }
            };
